#!/bin/sh

CUR=$(gcloud config list | grep account | awk -F'= ' '{print $2}')
ENVS=("oops.jybaek@gmail.com" "yapkaggle@gmail.com" "happy1234@gmail.com" "test0711@gmail.com")
result=$(dialog --menu "Choose account: (CUR) ${CUR}" \
		30 50 20 \
		$(for ((i = 0; i < ${#ENVS[@]}; i++));do echo "$i ${ENVS[$i]} ";done) \
		3>&2 2>&1 1>&3)

for ((i = 0; i < ${#ENVS[@]}; i++));do
	if [ "$result" == "0" ];then
		gcloud config set account oops.jybaek@gmail.com
		gcloud config set project gcp-ml-163504
		gcloud config set compute/zone us-central1-c
		break
	elif [ "$result" == "1" ];then
		gcloud config set account yapkaggle@gmail.com
		gcloud config set project yapkaggle-188300
		gcloud config set compute/zone us-east1-b
		break
	fi
done
