#!/bin/sh
#------------------------------------------------------
# Precondition
#------------------------------------------------------
# $ sudo apt-get install dialog
# $ sudo apt-get install expect
#------------------------------------------------------


dialog --title 'Welcome' --msgbox 'xshell이 그립습니다...\n
더 강력한 툴이 되기를...
\n\n\noops.jybaek@gmail.com
		' 10 40

# XXX. If you want to add a server, please edit it here.
result=$(dialog --menu "Choose one:" \
		   30 50 20 \
		   1 "10.52.3.119" \
		   2 "10.52.3.120" \
		   3 "10.52.3.121" \
		   4 "10.52.3.103 (아무개)" \
		   5 "10.52.3.115 (개똥이)" \
		   6 "test.example.com" \
		   3>&2 2>&1 1>&3)

conn_root_ssh() 
{
	SERVER=$1
	ID=$2
	PASSWD=$3

	ssh-keygen -R ${SERVER}

	expect -c "spawn ssh ${ID}@${SERVER}"\
	-c "trap {	 set rows [stty rows];  set cols [stty columns]; stty rows \$rows columns \$cols < \$spawn_out(slave,name);} WINCH" \
	-c "expect -re \"\(yes/no\)? \"" \
	-c "send \"yes\r\"" \
	-c "expect -nocase -re \"암호|password\"" \
	-c "send \"${PASSWD}\r\"" \
	-c "interact"
}

conn_admin_ssh() 
{
	SERVER=$1
	ID=$2
	PASSWD1=$3
	PASSWD2=$4

	ssh-keygen -R ${SERVER}

	expect -c "spawn ssh ${ID}@${SERVER}"\
	-c "trap {	 set rows [stty rows];  set cols [stty columns]; stty rows \$rows columns \$cols < \$spawn_out(slave,name);} WINCH" \
	-c "expect -re \"\(yes/no\)? \"" \
	-c "send \"yes\r\"" \
	-c "expect -nocase -re \"암호|password\"" \
	-c "send \"${PASSWD1}\r\"" \
	-c "expect -re \"~]\"" \
	-c "send \"su -\r\"" \
	-c "expect -nocase -re \"암호|password\"" \
	-c "send \"${PASSWD2}\r\"" \
	-c "interact"
}

conn_insecure_ssh()
{
	SERVER=$1
	ID=$2

	passwd=$(dialog --title "Password" \
			--clear \
			--insecure \
			--passwordbox "Enter your password" 10 30 3>&2 2>&1 1>&3)

	if [ "$?" = 1 ];then
		echo "terminated.."
		exit 255
	fi

	conn_root_ssh "$1" "$2" "$passwd"
}

# XXX. If you want to add a server, please edit it here.
case "$result" in
	1)
		conn_root_ssh "10.52.3.119" "root" "개똥이"
		;;
	2)
		conn_root_ssh "10.52.3.120" "root" "소똥이"
		;;
	3) 
		conn_root_ssh "10.52.3.121" "root" "말숙이"
		;;
	4) 
		conn_root_ssh "10.52.3.103" "root" "홍길동"
		;;
	5) 
		conn_admin_ssh "10.52.3.115" "root" "배두나" "password"
		;;
	6) 
		conn_insecure_ssh "test.example.com" "root"
		;;
esac

exit 0
