#!/bin/sh
#------------------------------------------------------
# Precondition
#------------------------------------------------------
# $ sudo apt-get install dialog
# $ sudo apt-get install expect
#------------------------------------------------------


dialog --title 'Welcome' --msgbox 'xshell이 그립습니다...\n
더 강력한 툴이 되기를...
\n\n\noops.jybaek@gmail.com
		' 10 40

# XXX. If you want to add a server, please edit it here.
result=$(dialog --menu "Choose one:" \
		   30 50 20 \
		   1 "10.52.3.119" \
		   2 "10.52.3.120" \
		   3 "10.52.3.121" \
		   4 "10.52.3.103 (아무개)" \
		   5 "10.52.3.115 (개똥이)" \
		   3>&2 2>&1 1>&3)

conn_ssh() 
{
	echo $1 $2 $3
	SERVER=$1
	ID=$2
	PWD=$3

	ssh-keygen -R ${SERVER}

	expect -c "spawn ssh ${ID}@${SERVER}"\
	-c "expect -re \"\(yes/no\)? \"" \
	-c "send \"yes\r\"" \
	-c "expect -re \"password:\"" \
	-c "send \"${PWD}\r\"" \
	-c "interact"
}

echo $result;

# XXX. If you want to add a server, please edit it here.
case "$result" in
	1)
		conn_ssh "10.52.3.119" "root" "개똥이"
		;;
	2)
		conn_ssh "10.52.3.120" "root" "소똥이"
		;;
	3) 
		conn_ssh "10.52.3.121" "root" "말숙이"
		;;
	4) 
		conn_ssh "10.52.3.103" "root" "홍길동"
		;;
	5) 
		conn_ssh "10.52.3.115" "root" "배두나"
		;;
esac

exit 0
